### PR TITLE
Prepare repository to be installed as a package via pip

### PR DESCRIPTION
**Pull request by albertaparicio**
I have created the needed files to install this package with `pip`. With the changes in this PR, the package can be installed locally i.e. `whatstk $ pip install .`

There are, however a few points that should be decided before we publish it, namely:

- Are we going to officially support Python 2.x?
- How mature is this project? (Beta, Stable?)
    - What is the version number of this package? (0.x or 1.x?)

I think that until these issues are not clarified, we should not publish the package on PyPi

### CODE REVIEW

**Comment by albertaparicio** [comment]
I agree on setting the project status as alpha.

Regarding Python 2.x, I'll try and run the code as is on version 2.7.14 and check what needs to be refactored

**Comment by albertaparicio** [comment]
There is no reason in particular. I proposed this idea having in mind that maybe someone would need to use this package with version 2.x in the future.

I have no problem in only supporting 3.x

**Comment by kafran** [comment]
I'm pretty new to python, but for what I have seem and learn, python 3 is broadly adopted for data science now. I'm not even minding into go to learn python 2.

**Comment by lucasrodes** [comment]
Definitely, if you are new to Python just go for 3. Backwards compatibility with Python 2 would be great, but is not a top priority I would say.

**Comment by lucasrodes** [comment]
@albertaparicio Could you please create a pull request for this issue for the develop branch instead of master branch?

**Pull request merged**
