### PR TITLE
Updated Links

### PR DESCRIPTION
**Pull request by batmanscode**
Just updated some links, the previous ones were sending me to a 404 page.

image

### CODE REVIEW

**Comment by lucasrodes** [comment]
Hi @batmanscode, thanks for your contribution. I believe I updated these links in branch [develop](https://github.com/lucasrodes/whatstk/tree/develop) and forgot to merge back to main.

Thanks once again for raising the issue! I'll proceed to update `main` branch with `develop`.

**Comment by lucasrodes** [comment]
See PR #111 to track this issue

**Comment by lucasrodes** [comment]
Should have been fixed in https://github.com/lucasrodes/whatstk/commit/0ceb3f77effeb34f86e17152b2e20964ed629f44

**Comment by batmanscode** [comment]
Ah I see, I actually hadn't seen till #109 after I submitted the PR.

Sure thing 😃. And btw thanks for creating this library. I was trying to convert the whatsapp txt into a pandas dataframe and this library made everything super easy!

**Pull request closed without merging**
